# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'GAP in Algebraic Research'
tagline:          'A GAP Summer School'
description:      'Summer School: Nov 19 - 22'
location:         'RWTH Aachen University'
url:              https://lbfm-rwth.github.io
baseurl:          /gap-in-algebraic-research-2018


exclude: [ "LICENSE.hyde.md", "README.hyde.md", "program.aux", "program.log", "program.out", "program.tex", "misc" ]
include: [ ]
