# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'GAP Days 2017, Fall'
tagline:          'A GAP workshop'
description:      'Workshop: Aug 30 - Sep 1, 2017<br> Code sprint: Sep 4-8, 2017'
location:         'University of Siegen'
url:              http://gapdays.de
baseurl:          /gapdays2017-fall


exclude: [ "program.aux", "program.log", "program.out", "program.tex", "misc" ]
include: [ "program.pdf" ]
