# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'GAP Days Fall 2017'
#tagline:          'A GAP school'
#description:      'School: Sep 14-18, 2015<br> Code sprint: Sep 19-23, 2015'
description:      'Code sprint: Sep 4-8, 2017'
location:         'Uni Siegen'
url:              http://gapdays.de
baseurl:          /gapdays2017-fall


exclude: [ "program.aux", "program.log", "program.out", "program.tex", "misc" ]
include: [ "program.pdf" ]
