# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'GAP Days 2017, Fall'
#tagline:          'A GAP school'
description:      'September 2017'
location:         'Uni Siegen'
url:              http://gapdays.de
baseurl:          /gapdays2017-fall


exclude: [ "program.aux", "program.log", "program.out", "program.tex", "misc" ]
include: [ "program.pdf" ]
